name: YouScope CI
on:
  push:
    branches:
      - master

jobs:
  nightly:
    name: Build YouScope
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew createInstallers

      - name: Upload 64bit installer as artifact
        uses: actions/upload-artifact@v4
        with:
          name: YouScope_64bit_Installer.exe
          path: build/distributions/YouScope_64bit_Installer.exe

      - name: Upload 32bit installer as artifact
        uses: actions/upload-artifact@v4
        with:
          name: YouScope_32bit_Installer.exe
          path: build/distributions/YouScope_32bit_Installer.exe

      - name: Upload 32/64bit installer as artifact
        uses: actions/upload-artifact@v4
        with:
          name: YouScope_3264bit_Installer.exe
          path: build/distributions/YouScope_3264bit_Installer.exe

      # Create or update release (associating with branch or tag)
      - name: Create or Update Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: nightly-${{ github.run_number }}      # Use a unique tag per run, adjust as you want
          release_name: Nightly Build ${{ github.run_number }}
          draft: false
          prerelease: true
      
      # Upload the 64bit installer to the release
      - name: Upload 64bit installer to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/distributions/YouScope_64bit_Installer.exe
          asset_name: YouScope_Installer_${{ github.run_number }}-64bit.exe
          asset_content_type: application/exe

      # Upload the 32bit installer to the release
      - name: Upload 32bit installer to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/distributions/YouScope_32bit_Installer.exe
          asset_name: YouScope_Installer_${{ github.run_number }}-32bit.exe
          asset_content_type: application/exe

      # Upload the 32/64bit installer to the release
      - name: Upload 32/64bit installer to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/distributions/YouScope_3264bit_Installer.exe
          asset_name: YouScope_Installer_${{ github.run_number }}-3264bit.exe
          asset_content_type: application/exe
